[[LibYAML]]
arch = "aarch64"
git-tree-sha1 = "626e8552a08553567af3a997aa091b94dce1eba4"
os = "macos"

    [[LibYAML.download]]
    sha256 = "48272b81edc333fdcfbb2e69520e9f1a9992ae3225946c636a944267c77a42f3"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.aarch64-apple-darwin.tar.gz"
[[LibYAML]]
arch = "aarch64"
git-tree-sha1 = "4a0a57c1794eca0d84281da2a2c44ca7c21c40a1"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "ed330fb502a7ca1fbb15d50d04af984747d9b5d393d73bd2432219ac2c1e088b"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.aarch64-linux-gnu.tar.gz"
[[LibYAML]]
arch = "aarch64"
git-tree-sha1 = "8125709c691de36622a5b965e7fba2a0cd24d61c"
libc = "musl"
os = "linux"

    [[LibYAML.download]]
    sha256 = "2e8c95f78f49d83b6d54133e29e9d1b22c7e22d4b882057df8f1325f15657346"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.aarch64-linux-musl.tar.gz"
[[LibYAML]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6ccc63add8a1cd87cd2d9b6b9ded6b09091e0b5"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "90deb8564314cdc68b5ac15606de5bc39dc0a9f1ddf07072508f561656ee20e4"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.armv6l-linux-gnueabihf.tar.gz"
[[LibYAML]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0599ef4d886f40259077162ed0622235ab804f3a"
libc = "musl"
os = "linux"

    [[LibYAML.download]]
    sha256 = "bedfcc16b7fc8ce16e079051a199860f90fad2a4232ba912a73105e8b04701e8"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.armv6l-linux-musleabihf.tar.gz"
[[LibYAML]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7bb8bc66f37efe678ec4396fb211329ff9eed1c"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "a0b86a3b02796e6a18b0bbd3f67db07e92de7e96f4bcaf96e04b7d331dbbf94b"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.armv7l-linux-gnueabihf.tar.gz"
[[LibYAML]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30c1c862ed26cbce99ee88a220a43be3a75cecc2"
libc = "musl"
os = "linux"

    [[LibYAML.download]]
    sha256 = "517a64e2e940c517773ec84db674817f97b6eaec578dded2a161e62fb25c0be5"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.armv7l-linux-musleabihf.tar.gz"
[[LibYAML]]
arch = "i686"
git-tree-sha1 = "2539da5c31e1249dfb95bcce947043ce0d00b954"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "26b617bbf4eecd9101bc2ccdb11794f0ab9199a479909cef01d22055f22c5092"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.i686-linux-gnu.tar.gz"
[[LibYAML]]
arch = "i686"
git-tree-sha1 = "1cbbead3b33ba0df1d8abfc88f41531f7c98995d"
libc = "musl"
os = "linux"

    [[LibYAML.download]]
    sha256 = "5fe6a2d133d7e2469d1951ebdffa6f96b7d4775b53b36dd8a0fe0a9d628d74c1"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.i686-linux-musl.tar.gz"
[[LibYAML]]
arch = "i686"
git-tree-sha1 = "84529fb81053310f58ad86eeb710d7ba97627d85"
os = "windows"

    [[LibYAML.download]]
    sha256 = "72823070e837649d9c505c72a2040e33ebed987be34e542811c59d953335f998"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.i686-w64-mingw32.tar.gz"
[[LibYAML]]
arch = "powerpc64le"
git-tree-sha1 = "697fb9e6affa04f154745d8e61fae80fcda44485"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "88488fa179b65214644257d3f2f35770458d8230f9464a3f307cae39d1cd9b43"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.powerpc64le-linux-gnu.tar.gz"
[[LibYAML]]
arch = "x86_64"
git-tree-sha1 = "143e51ae2279f3e3e908074e4306aca1e5183daf"
os = "macos"

    [[LibYAML.download]]
    sha256 = "35f936c9419c6f288d0f3c56ff16a9719209e36d9bd1a7faff2b77288f616b33"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.x86_64-apple-darwin.tar.gz"
[[LibYAML]]
arch = "x86_64"
git-tree-sha1 = "d7e4160608b41ccad638477f46cd208ff7bfa6a2"
libc = "glibc"
os = "linux"

    [[LibYAML.download]]
    sha256 = "1e7ba0da74582fdb93f678d9cb6b2ac6dc43c3db3caba2e65376c4ec375e9006"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.x86_64-linux-gnu.tar.gz"
[[LibYAML]]
arch = "x86_64"
git-tree-sha1 = "d2a2859eefba5984f24bf730027b98d689342b40"
libc = "musl"
os = "linux"

    [[LibYAML.download]]
    sha256 = "a290d02de97eeeaa295221023924344ca00d75fc9eb8e4636bbf1f044d336991"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.x86_64-linux-musl.tar.gz"
[[LibYAML]]
arch = "x86_64"
git-tree-sha1 = "a26685a0009039339a3b2dcec0a1f2f2f7f1bf90"
os = "freebsd"

    [[LibYAML.download]]
    sha256 = "0fef001fee1583fac1a57bbefd8482494e06b48f9acf8a85cb04504d0b8668a5"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.x86_64-unknown-freebsd.tar.gz"
[[LibYAML]]
arch = "x86_64"
git-tree-sha1 = "9793907a368df3b3dc5c29ab6d5146e959ae396c"
os = "windows"

    [[LibYAML.download]]
    sha256 = "adeb9c17ddb640d04863e2d16c7c26c4638b741e07c9d9c4acc07b8d74a10f09"
    url = "https://github.com/JuliaBinaryWrappers/LibYAML_jll.jl/releases/download/LibYAML-v0.2.6+0/LibYAML.v0.2.6.x86_64-w64-mingw32.tar.gz"
