# Autogenerated wrapper script for LibYAML_jll for x86_64-apple-darwin
export libyaml

JLLWrappers.@generate_wrapper_header("LibYAML")
JLLWrappers.@declare_library_product(libyaml, "@rpath/libyaml-0.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libyaml,
        "lib/libyaml-0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
