# Autogenerated wrapper script for LibYAML_jll for x86_64-w64-mingw32
export libyaml

JLLWrappers.@generate_wrapper_header("LibYAML")
JLLWrappers.@declare_library_product(libyaml, "libyaml-0-2.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libyaml,
        "bin/libyaml-0-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
